### ISSUE TITLE
r4

### ISSUE THREAD

**Issue by Libereau** [wapiflapi/exrs#4]
Hi there, 

I don't know if this git is still up, but I've found the reverse exercices, and it's pretty cool. 
The fact is that that i've solved r1 to r3 easily, but i'm stuck to r4. Do you have any advices to complete this exercices ? I've found a huge array of strings, but I don't know what to do with it..

Thanks, 
Libero

**Comment by wapiflapi** [comment]
Hi @Libereau 

Thank you for your interest in these challenges and wanting to learn reverse engineering :-)

Regarding your problem, what have you tried? What did you find appart from the huge array of strings? Did you look at what the code does? If so what do you believe it does? Did you use any tools like radare or ghidra to reverse engineer the code?

I suggest asking for help in a community dedicated to that, I would suggest stack overflow or perhaps joining one of the discord communities such as https://themanyhats.club/invite/

I'm really sorry but I don't want the issues on this git repo to turn into a help forum because I'd rather we keep it clean for actual bugs with the challenges. That's why I'm going to close this issue because otherwise it shows up in my "TODO" stuff on github :-)

Feel free to send me an email at wapiflapi@gmail.com to continue this conversation if you're still stuck and can't find a place where you can learn :-)
